enum doorTypes {
  INIT_DOORS = "INIT_DOORS",

  OPEN_DOOR_START = "OPEN_DOOR_START",
  OPEN_DOOR_SUCCESS = "OPEN_DOOR_SUCCESS",
  OPEN_DOOR_FAIL = "OPEN_DOOR_FAIL",

  RESET_DOOR_START = "RESET_DOOR_START",
  RESET_DOOR_SUCCESS = "RESET_DOOR_SUCCESS",
  RESET_DOOR_FAIL = "RESET_DOOR_FAIL",
}

export default doorTypes;


